# We scraping Yahoo Finance, baby

In [35]:
# Get important definitions from project root
from definitions import WEBDRIVER_PATH

# Import packages important to this project
# Analysis Packages
import statistics as stat
import requests as r
import pandas as pd
import numpy as np

# Text parsing packages
import re

# Web crawling packages
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup

In [53]:
number = '250,000,248'
na_number = '-'

clean_numeric(na_number)

0.0

In [54]:
# DEFINE FUNCTIONS
def clean_numeric(text, frmat = float):
    """
    Text numbers in text format. Cleans out characters that make conversion to int or float impossible.
    
    Returns the values in chosen frmat function (i.e. int or float)
    """
    clean_text = text
    
    # Define replacements
    rep = {',':'',
          '^\-$':'0'}
    
    for found, replaced in rep.items():
        clean_text = re.sub(found, replaced, clean_text)
        
    return(frmat(clean_text))

def create_webdriver():
    """
    Create and return a Chrome web driver for use in this app's scraping functions.
    
    We're using a webdriver instead of just raw requests, because yahoo finance income statement rows
    sometimes need to be expanded with an HTML button (like OpEx).
    """
    # Specify the file of the driver to be used
    driver_name = 'chromedriver.exe'
    
    # Instantiate driver options
    options = webdriver.ChromeOptions()
    
    # Specify driver options
    options.add_argument('--headless')
    options.add_argument('--ignore_certificate_errors')
    options.add_argument('--incognito')
    
    # Instantiate driver service
    service = Service(WEBDRIVER_PATH + driver_name)
    
    # Instantiate driver
    driver = webdriver.Chrome(service = service, options = options)
    
    return(driver)

def get_income_statement(webdriver, ticker_symbol):
    """
    Get income statement for company = ticker_symbol from yahoo finance.
    
    Only returns the set of divs on the page corresponding to income statement rows and its header.
    
    Recommended use case is passing the output to the following dictify_income() function to get a proper
    income statement dict with many more use cases.
    """
    url = 'https://finance.yahoo.com/quote/{}/financials'.format(ticker_symbol)
    # Open the page in webdriver
    driver.get(url)
    
    # Expand the OpEx row on the page
    driver.find_element(By.XPATH, '//button[@aria-label="Operating Expense"]').click()
    
    # Get the page's soup
    soup = BeautifulSoup(driver.page_source, 'lxml')
    
    # Get the income statement's heading
    statement_heading = soup.find('div',{'class':'D(tbhg)'}).select_one('div:first-child').find_all('div')
    
    # Get list of divs from the page source that correspond to income statement rows
    statement_rows = soup.find_all('div',{'data-test':'fin-row'})
    
    return(statement_heading, statement_rows)

def dictify_income(statement_heading, statement_rows):
    """
    Takes an income statement heading and a list of income statement rows as returned by get_income_statement().
    Literally, these are sets of divs from the yahoo finance page's dom.
    
    Gets rid of all the dom baggage and returns a simple dict of income statement rows.
    """
    # Instantiate the income_dict
    income_dict = dict()
    
    ## STEP 1: Get the years column before doing anything else. Requires special process.
    # We take indices [2:], because first two columns are the row name ("breakdown") and a blank column for formatting
    income_dict['Year'] = np.array([x.text for x in statement_heading[2:]])
    
    ## STEP 2.PREAMBLE: Establish the mode number of columns in the income statement
    # We'll use this to weed out subheader rows that have been expanded (subheader rows will show more columns than mode value)
    # Requires statistics package aliased as "stat"
    col_counts = list()
    for row in statement_rows:
        col_counts.append(len(row.find_all('div',{'data-test':'fin-col'})))
    col_mode = stat.mode(col_counts)
    
    ## STEP 2: Iterate through income statement rows and pull out the values into the dict
    for row in income_statement:
        # Get a list of the columns in the row
        cols = row.find_all('div',{'data-test':'fin-col'})
        
        # Check to see if column count == the col_mode we calculated above
        # If yes, it's safe for extraction into the dict
        # If no, it's an expanded subheader row, and we should skip it
        # Result is several rows for the components of OpEx and NO separate row for the OpEx aggregate
        if len(cols) == col_mode:
            
            # Light cleaning: get rid of commas, replace '-' with zero, format all values as floats rather than text
            rowvals = np.array([clean_numeric(x.text) for x in cols])
            rowname = row.select_one('div:first-child').find_all('div')[0].text
            
            income_dict[rowname] = rowvals
    
    return(income_dict)

In [11]:
### Set up the webdriver
driver = create_webdriver()

In [12]:
### Get the income statement's list of dom rows
income_heading, income_rows = get_income_statement(driver, 'INTC')

In [55]:
### Get income statement in convenient dict form
income_dict = dictify_income(income_heading, income_rows)

In [56]:
income_dict['Cost of Revenue'] / income_dict['Total Revenue']

array([0.4373423 , 0.43991678, 0.41443757, 0.3826643 , 0.37749558])

In [40]:
income_dict['Year']

array(['ttm', '12/31/2020', '12/31/2019', '12/31/2018', '12/31/2017'],
      dtype='<U10')

In [57]:
pd.DataFrame(income_dict)

,Year,Total Revenue,Cost of Revenue,Gross Profit,Selling General and Administrative,Research & Development,Depreciation Amortization Depletion,Operating Income,Net Non Operating Interest Income Expense,Other Income Expense,...,EBIT,EBITDA,Reconciled Cost of Revenue,Reconciled Depreciation,Net Income from Continuing Operation Net Minority Interest,Total Unusual Items Excluding Goodwill,Total Unusual Items,Normalized EBITDA,Tax Rate for Calcs,Tax Effect of Unusual Items
0,ttm,78474000.0,34320000.0,44154000.0,6358000.0,14796000.0,0.0,23000000.0,-416000.0,1413000.0,...,24608000.0,36329000.0,34320000.0,11721000.0,21102000.0,1413000.0,1413000.0,34916000.0,0.0,170464.0
1,12/31/2020,77867000.0,34255000.0,43612000.0,6180000.0,13556000.0,0.0,23876000.0,-504000.0,1706000.0,...,25707000.0,0.0,34255000.0,12239000.0,20899000.0,1706000.0,1706000.0,36240000.0,0.0,284902.0
2,12/31/2019,71965000.0,29825000.0,42140000.0,6150000.0,13362000.0,200000.0,22428000.0,484000.0,1146000.0,...,24547000.0,0.0,19199000.0,10826000.0,21048000.0,1146000.0,1146000.0,34227000.0,0.0,143250.0
3,12/31/2018,70848000.0,27111000.0,43737000.0,6750000.0,13543000.0,200000.0,23244000.0,126000.0,-53000.0,...,23785000.0,0.0,18226000.0,9085000.0,21053000.0,-53000.0,-53000.0,32923000.0,0.0,-5141.0
4,12/31/2017,62761000.0,23692000.0,39069000.0,7474000.0,13098000.0,177000.0,18320000.0,-235000.0,2267000.0,...,20998000.0,0.0,15740000.0,8129000.0,9601000.0,2499000.0,2499000.0,26628000.0,0.0,999600.0